runtime: python310  # Choose the Python version that matches your app
service: production-foodhak-score
instance_class: F4_1G  # Adjust this based on your needs and traffic

entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT app:app  # Using gunicorn config file for better control

env_variables:
  ENV: 'production'
  API_KEY: 'viJ8u142.NaQl7JEW5u8bEJpqnnRuvilTfDbHyWty'

# Optional if VPC connector is needed
vpc_access_connector:
  name: projects/central-muse-388319/locations/us-central1/connectors/vpc-access-connector

automatic_scaling:
  target_cpu_utilization: 0.65  # Increase threshold slightly for better performance under load
  min_instances: 7  # Keep a minimum of 5 instances to reduce cold starts
  max_instances: 20  # Increase the max number of instances to handle more traffic

# Health check settings (optional but recommended)
health_check:
  enable_health_check: true
  check_interval_sec: 10
  timeout_sec: 4
  healthy_threshold: 2
  unhealthy_threshold: 3
  restart_threshold: 60

# Increase request timeout if needed (default is 60 seconds)
handlers:
- url: /.*
  script: auto
  secure: always


